---
# tasks file for nginx
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: install nginx
  yum:
    name: nginx
    state: latest

- name: copy nginx configuration
  template: 
    src: nginx.conf.j2 
    dest: "{{nginx_config}}"

- name: copy vhost configuration
  template: 
    src: default.conf.j2 
    dest: "{{nginx_vhost_config}}"
  notify: restart nginx service

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: yes