---
# tasks file for laravel

- name: create directory
  file: 
    path: "{{nginx_docroot}}"
    state: directory

- name: clone git repository
  git:
    repo: "https://github.com/cretueusebiu/laravel-vue-spa.git"
    dest: "{{nginx_docroot}}"
    accept_hostkey: yes
    clone: yes

- name: copy .env file
  template: 
    src: .env.j2 
    dest: "{{nginx_docroot}}/.env"
    
- name: composer install
  composer:
    command: install
    working_dir: "{{nginx_docroot}}"

- name: change storage permission
  file:
    path: "{{nginx_docroot}}/storage"
    state: directory
    recurse: yes
    mode: "g+w,u+w,o+w"

- name: php artisan clear cache
  shell: "php artisan cache:clear"
  args:
    chdir: "{{nginx_docroot}}"

- name: php artisan key generate
  shell: "php artisan key:generate"
  args:
    chdir: "{{nginx_docroot}}"

# - name: php artisan jwt secret
#   expect:
#     command: "php artisan jwt:secret"
#     chdir: "{{nginx_docroot}}"
#     responses: 
#       Question:
#         \b(secret)\b: "y"
#     echo: yes

- name: php artisan migrate
  shell: "php artisan migrate"
  args:
    chdir: "{{nginx_docroot}}"

- name: npm install
  npm:
    path: "{{nginx_docroot}}"

- name: npm run production
  shell: "npm run production"
  args:
    chdir: "{{nginx_docroot}}"
