---

- name: set db root password
  mysql_user: 
    name: root 
    password: "{{dbrootpasswordnew}}"
  ignore_errors: true

- name: delete test database
  mysql_db: 
    name: test 
    login_user: root 
    login_password: "{{dbrootpasswordnew}}" 
    state: absent

- name: create application database
  mysql_db: 
    name: "{{dbname}}"
    login_user: root 
    login_password: "{{dbrootpasswordnew}}"
    state: present

- name: create application database user
  mysql_user: 
    name: "{{dbuser}}"
    password: "{{dbpassword}}"
    login_user: root
    login_password: "{{dbrootpasswordnew}}"
    priv: '*.*:ALL'