---

- include: setup-CentOS.yml
  when: ansible_distribution == 'CentOS'

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: database.yml
  when: deploy_app == 'laravel'
